### ISSUE TITLE
Has no license

### ISSUE THREAD

**Issue by tkelman** [gdziadkiewicz/ExpressionUtils.jl#4]
This is re-posting https://github.com/zachallaun/ExpressionUtils.jl/issues/1 - without a license statement, you haven't granted any users permission to actually use this code. Would likely need acknowledgement by @zachallaun and any other past contributors that they agree to license their contributions under whatever you pick. MIT would be most common for Julia packages.

**Comment by zachallaun** [comment]
Thanks for the ping – I've added MIT to zachallaun/ExpressionUtils.jl.

**Comment by gdziadkiewicz** [comment]
@tkelman
I agree to license my contributions under MIT license. @timholy what about your contributions?

**Comment by timholy** [comment]
Likewise.
